language: python

services:
  - docker

python:
  - "3.6"

script:
  - python setup.py flake8
  - cp docker/.env.example docker/.env
  - docker build . -t pyslackers/sirbot.pythondev -f docker/Dockerfile
  - docker-compose -f docker/docker-compose.ngrok.yml build
  - docker-compose -f docker/docker-compose.prod.yml build
  - docker-compose -f docker/docker-compose.yml build

before_deploy:
  - pip install dothub

deploy:
  provider: script
  script: "yes | dothub repo --owner pyslackers --repository sirbot-pythondev push"
  on:
    repo: pyslackers/sirbot-pythondev
    branch: master
    python: '3.6'
