version: '3'

services:
  sirbot-pythondev:
    image: pyslackers/sirbot-pythondev:master
    container_name: sirbot-pythondev
    env_file:
      - /etc/sirbot/.env
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - /etc/sirbot:/etc/sirbot
      - /var/log/sirbot:/var/log/sirbot
      - /var/lib/sirbot:/var/lib/sirbot
