version: '3'

services:
  sirbot-pythondev:
    image: pyslackers/sirbot-pythondev:master
    container_name: sirbot-pythondev
    env_file:
      - /home/sirbot/.env
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - /home/sirbot/sirbot/config:/etc/sirbot
      - /home/sirbot/log:/var/log/sirbot
      - /home/sirbot/data:/var/lib/sirbot
